# Add Default Pricing for each Region / Size


# --- !Ups

 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID,HOURLY_PRICE) VALUES('nyc1','New York 1','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','64','0.0870');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','64','0.0870');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','61','0.2660');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','60','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','69','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','70','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc2','New York 2','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','64','0.0870');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams1','Amsterdam 1','61','0.2660');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','61','0.2660');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','64','0.0870');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','61','0.2660');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','60','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','70','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('ams2','Amsterdam 2','69','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','64','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','61','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','60','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','70','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sfo1','San Francisco 1','69','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','60','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','63','0.0330');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','66','0.0200');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','62','0.0460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','64','0.0870');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','65','0.1460');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','61','0.2660');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','60','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','70','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('sgp1','Singapore 1','69','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','70','0.0000');
 REPLACE INTO DO_REGIONS(SLUG,NAME,SIZEID, HOURLY_PRICE) VALUES('nyc1','New York 1','69','0.0000');

# --- !Downs
